FROM mcr.microsoft.com/windows/server:ltsc2022-KB5012604-amd64
COPY MinGit.zip /tmp/
COPY nodejs.msi /tmp/
RUN powershell -Command Expand-Archive /tmp/MinGit.zip -DestinationPath /MinGit/; \
$env:PATH = $env:PATH + ';c:\MinGit\cmd\'; \
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name Path -Value $env:PATH
RUN msiexec.exe /i c:\tmp\nodejs.msi /quiet
RUN npm i -g @vue/cli
RUN mkdir c:\src
RUN cd c:\src
